channels:
- conda-forge
dependencies:
- python=3.8
- pip
- pip:
  - azureml-core==1.53.0
  - azureml-defaults==1.53.0
  - azureml-contrib-services==1.53.0
  - pandas
  - joblib
name: basic_inference_env
