# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Definition of infra-related environment variables

variables:

  # DEV Environment
  ENVIRONMENT: DEV
  RESOURCE_GROUP: rg-mlops-base
  LOCATION: westeurope
  NAMESPACE: mlopsbasedev
  AMLWORKSPACE: $(NAMESPACE)aml
  STORAGEACCOUNT: $(NAMESPACE)sa
  KEYVAULT: $(NAMESPACE)kv
  APPINSIGHTS: $(NAMESPACE)ai
  CONTAINERREGISTRY: $(NAMESPACE)cr
  SERVICECONNECTION_RG: conn-mlopsbase-rg
  SERVICECONNECTION_WS: conn-mlopsbase-amldev
